services:
  # Backend Server
  server:
    image: itsankit123/taskify:server
    container_name: taskify-server
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
      - MONGODB_URI=${MONGODB_URI}
      - JWT_SECRET=${JWT_SECRET}
      - PORT=5000
    networks:
      - taskify-network

  # Frontend Client
  client:
    image: itsankit123/taskify:client
    container_name: taskify-client
    ports:
      - "3000:3000"
    environment:
      - VITE_API_URL=http://localhost:5000/api
    depends_on:
      - server
    networks:
      - taskify-network

networks:
  taskify-network:
    driver: bridge